- name: install list of packes
  hosts: localhost
  become: yes
  tasks:
    - name: install packges 
      ansible.builtin.dnf: 
        name: "{{item}}"
        state: latest 
      loop:
        - git
        - gzip
        - nginx