- name: install and start nginx
  hosts: web
  become: yes
  tasks:
  - name: nginx install
    ansible.builtin.yum:
      name: nginx
      state: latest
  - name: nginx start
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
