---
- name: configure ba kend server
  hosts: backend 
  become: yes 
  tasks:
  - name: disable node js 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodes js 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js 
    ansible.builtin.dnf: 
      name: nodejs
      state: installed 

  - name: create expense user 
    ansible.builtin.user:
      name: expense 

  - name: create folder 
    ansible.builtin.command: mkdir /app