---
- name: install mysql server and configure 
  hosts: frontend
  become: yes 
  tasks:
    - name: install mysql 
      ansible.builtin.dnf:
        name: mysql-server
        state: latest 

    - name: start and enabled mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes