---
- name: install mysql server and configure 
  hosts: db
  become: yes 
  vars:
    user: root 
  vars_prompt:
    - name: "password"
      prompt: "enter db password"
      private: true 
  tasks:
    - name: install mysql 
      ansible.builtin.dnf:
        name: mysql-server
        state: latest 

    - name: start and enabled mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    
    - name: enable db password 
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{password}}