---
- name: install mysql server and configure 
  hosts: db
  become: yes 
  vars:
    login_password: db.devopslearning2026.store
  vars_prompt:
    - name: "mysql_root_password"
      prompt: "enter db password"
      private: true 
  tasks:
    - name: install mysql 
      ansible.builtin.dnf:
        name: mysql-server
        state: latest 

    - name: start and enabled mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

      # check password is already setup or not
    - name: check DB connection
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: "{{ login_host }}"
      filter: version
      ignore_errors: yes
      register: mysql_connection_output
    
    # - name: enable db password 
    #   ansible.builtin.shell: mysql_secure_installation --set-root-pass {{password}}